// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CUONGDB.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230625115103_Create_Foreignkey_RUN")]
    partial class Create_Foreignkey_RUN
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.8");

            modelBuilder.Entity("CUONGDB.Models.Faculty", b =>
                {
                    b.Property<string>("FCTID")
                        .HasColumnType("TEXT");

                    b.Property<string>("FCTName")
                        .HasColumnType("TEXT");

                    b.HasKey("FCTID");

                    b.ToTable("Faculty");
                });

            modelBuilder.Entity("CUONGDB.Models.HUU", b =>
                {
                    b.Property<string>("HUUID")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("HUUName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("HUUSL")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("HUUSL02")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("HUUSđt")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("HUUID");

                    b.ToTable("HUU");
                });

            modelBuilder.Entity("CUONGDB.Models.LOPHOC", b =>
                {
                    b.Property<int?>("MaLop")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("SoLuong")
                        .HasColumnType("TEXT");

                    b.Property<string>("TenLop")
                        .HasColumnType("TEXT");

                    b.HasKey("MaLop");

                    b.ToTable("LOPHOC");
                });

            modelBuilder.Entity("CUONGDB.Models.RUN", b =>
                {
                    b.Property<string>("RUNID")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("FCTID")
                        .HasColumnType("TEXT");

                    b.Property<string>("RUNADDRESS")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("RUNNAME")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("RUNSEX")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("RUNID");

                    b.HasIndex("FCTID");

                    b.ToTable("RUN");
                });

            modelBuilder.Entity("CUONGDB.Models.RUN", b =>
                {
                    b.HasOne("CUONGDB.Models.Faculty", "Faculty")
                        .WithMany()
                        .HasForeignKey("FCTID");

                    b.Navigation("Faculty");
                });
#pragma warning restore 612, 618
        }
    }
}
